### ISSUE TITLE
IF语句的bug

### ISSUE THREAD

**Issue by ironyyy** [paladin-t/my_basic#1]
IF语句的条件不成立时，如果下面没有ELSE语句的话，会出现bug，比如
i = 1
if i>1 Then 
i = 2
endif
print i
就无法执行，但是加上ELSE语句就可以，如下所示
i = 1
if i>1 Then 
i = 2
else
i = 3
endif
print i

**Comment by ironyyy** [comment]
嵌套之后也会出现问题
i = 1
if i>1 Then 
	i = 2
	if false Then
		i =2
	else
		i =2
	endif
else
	i = 5
endif
print i

**Comment by paladin-t** [comment]
Fixed in r71, ver 1.1.0061. Thank you for the feedback.
已在 r71 版本修复，对应版本号 1.1.0061。感谢您的反馈。
