### ISSUE TITLE
interpreter crash with unmatched if - endif

### ISSUE THREAD

**Issue by yukini3** [paladin-t/my_basic#11]
Hi,
Run the following code and you'll get an exception error. The interpreter should stop and generate some sort of error message (unmatched if-endif?) but instead, it crashes. Any idea?

a=3
if a <> 3 then
 print "a<>3";
else
 a=10
 if a >= 7 and a < 19 then
  print "we're in "
  if (a mod 2) = 0 then
    print "0";
  else
    print "1";
  endif
 else
  print "we're out ";
 endif

**Comment by paladin-t** [comment]
Hi,

Thanks for informing. I've fixed this crash bug. Please check.

**Comment by yukini3** [comment]
Thank you for the quick fix. I have confirmed that this bug has been fixed.
