### ISSUE TITLE
Generic Progamming Support.

### ISSUE THREAD

**Issue by keito940** [paladin-t/my_basic#12]
Like From C++&D-Lang Template.
generic function
```BAS
generic add(A,B)
return A + B 
genericend

print add(1,2)
print add("abc","def")
```
generic class
```BAS
generic class(class T)
obj = T
genericend

tempint = obj(1)
temphello = obj("hello world")

print tempint
print temphello
```

Sample factrical(generic)
```BAS
generic fact(num)
if num = 1 then
return 1
else 
return fact(num-1)*num
endif
genericend

print fact(10) REM =3628800
```

Support plz.

**Comment by paladin-t** [comment]
Hi,

Thank you for your suggestion.

IMHO, templates are used for type inference, where "type" here means type of variable with static typed languages.

In a same way which other scripting languages (as Python, Ruby, Lua and so on) were implemented, MY-BASIC is a dynamic typed language, thus a variable doesn't have a type, but a value does. So variables in MY-BASIC can store no matter what type of value, technically it's already "generic".

A function which accepts multiple types of arguments, for instance:

~~~~~~~~~~bas
def add(a, b)
	return a + b
enddef

print add(1, 2);
print add("abc", "def");
~~~~~~~~~~

Another example shows that a variable can be assigned with multiple types of value.

~~~~~~~~~~bas
class clz
endclass

foo = 123
print type(foo);
foo = 22 / 7
print type(foo);
foo = "hello"
print type(foo);
foo = list()
print type(foo);
foo = new(clz)
print type(clz);
~~~~~~~~~~

Any more feedback is appreciated.
