### ISSUE TITLE
Passing a struct

### ISSUE THREAD

**Issue by jacmoe** [paladin-t/my_basic#14]
I have this struct:

```c
typedef struct SpriteSheet {
    Buffer **sprites;
    int rows, cols;
    int width, height;
} SpriteSheet;

```

And my library passes it around by value, like this:

```c
void nasl_draw_text(Buffer *b, SpriteSheet ascii, int x, int y, const char *fmt, ...);
```

Since it is not a reference nor a pointer, how do I instruct MY-BASIC to handle it?

**Comment by paladin-t** [comment]
There is a byte array field in the `mb_value_t` struct, which you can store some bytes in. For example passing a struct (sizeof(64) bytes) through MY-BASIC:

```c
typedef struct Tag {
	char c0[64];
} Tag;

mb_static_assert(sizeof(mb_val_bytes_t) >= sizeof(Tag));

static int test0(struct mb_interpreter_t* s, void** l) {
	int result = MB_FUNC_OK;
	mb_value_t val;

	mb_assert(s && l);

	mb_check(mb_attempt_open_bracket(s, l));

	mb_check(mb_attempt_close_bracket(s, l));

	Tag tag;
	for (int i = 0; i < sizeof(tag.c0) - 1; ++i)
		tag.c0[i] = '*';
	tag.c0[sizeof(tag.c0) - 1] = '\0';
	val.type = MB_DT_USERTYPE;
	memset(&val.value.bytes, 0, sizeof(mb_val_bytes_t));
	memcpy(&val.value.bytes, &tag, sizeof(Tag));

	mb_check(mb_push_value(s, l, val));

	return result;
}

static int test1(struct mb_interpreter_t* s, void** l) {
	int result = MB_FUNC_OK;
	mb_value_t val;

	mb_assert(s && l);

	mb_check(mb_attempt_open_bracket(s, l));

	mb_make_nil(val);
	mb_check(mb_pop_value(s, l, &val));

	mb_check(mb_attempt_close_bracket(s, l));

	Tag tag;
	memcpy(&tag, &val.value.bytes, sizeof(Tag));

	printf(tag.c0);

	return result;
}
```

Test it with:

```bas
test1(test0())
```

By default, the byte array typed `mb_val_bytes_t` is defined as large as maximum of sizes of `void*`, `unsigned long`, `int_t`, `real_t`, in `my_basic.h`. Make sure you've redefined it large enough to store your struct:

```c
typedef unsigned char mb_val_bytes_t[64];
```

**Comment by paladin-t** [comment]
I'll document this feature later.

**Comment by jacmoe** [comment]
I will  try this! Thanks a lot 😃 

I have to say, that the MY-BASIC documentation is almost too good! 🥇

**Comment by jacmoe** [comment]
I just finished binding my SpriteSheets to MY-BASIC - it works wonderfully.
For me, this issue has been resolved.
Thanks a lot! :)
