### ISSUE TITLE
There is a bug in STR 

### ISSUE THREAD

**Issue by Beyond07** [paladin-t/my_basic#15]
when i do this like "STR(2334)" ,it will fail .  Do you have something to solve this ?

the error information as below:

Debug Assertion Failed!

Program: ...roject\Debug\my_basic.exe
File: f:\dd\vctools\crt\crtw32\misc\dbgheap.c
Line: 1322

Expression: _CrtIsValidHeapPointer(pUserData)

**Comment by paladin-t** [comment]
Thanks for the issue report.

Could you post some more detail about how to reproduce this issue? What was the script context, did it occur before or after invoking any registered functions, or basically what compiler version was it?

**Comment by Beyond07** [comment]
input "STR(223)",then run.
if use "print(STR(223))",it won't happen .
thanks for your help

**Comment by paladin-t** [comment]
Fixed in [revision 869](https://github.com/paladin-t/my_basic/commit/305f698b9a31e625e091bb7f330c0201df39ee76).

**Comment by Beyond07** [comment]
You are so cool! thanks a lot ,I will try later.
