### ISSUE TITLE
Porting for FUZIX.

### ISSUE THREAD

**Issue by keito940** [paladin-t/my_basic#16]
FUZIX. Micro System Operating System.
https://github.com/EtchedPixels/FUZIX
...but Porting Now?
SDCC is ANSI C Support.
FUZIX users will be delighted as well.

**Comment by paladin-t** [comment]
Hi,

I'd like to help MY-BASIC running on more platforms. FUZIX looks nice. But I'm sorry I don't have enough time to learn details about this OS and toolchain for the moment. MY-BASIC can be compiled with various popular compilers now. Any compile issue report is appreciated. Maybe I'll take a try on FUZIX someday.

**Comment by paladin-t** [comment]
I've tried to compile MY-BASIC with SDCC, but it appears that SDCC is implemented following an ancient way: without allowing `struct` passed to and from functions. It's up to compiler vendors about whether a caller or callee is in charge of storing, pushing, popping the memory of `struct` parameter and return value; furthermore, there might be issues using more than one compiler to compile and link one program with `struct` passing. But it should be supported as a part of the [standard](http://c-faq.com/struct/firstclass.html) anyway. I don't see the sense of not supporting it if SDCC is not supposed to link with libs generated by other compilers.

It would change a lot of current implementation and interface; but it's not wise to make changes to C API now, for just supporting a not widely used compiler. Anyway, I'll consider adding some passing by pointer only API in the v2.0. So this won't be fixed for the moment.
