### ISSUE TITLE
Wrong function reached error on if-else-endif nest

### ISSUE THREAD

**Issue by yukini3** [paladin-t/my_basic#17]
Hello,
with the latest build, I run the if-else-endif program with error. It was able to run on older build.  Since it was able to run on older build, I wonder if there is any changes on syntax of if-then-else-endif. 

Copy of screen attached:

MY-BASIC Interpreter Shell - 1.2
Copyright (C) 2011 - 2017 Wang Renxin. All Rights Reserved.
For more information, see https://github.com/paladin-t/my_basic/.
Input HELP and hint enter to view help information.
]    if a = 0 then
]        if b = 0 then
]            print "Start";
]        endif
]    else
]        print "A"
]    endif
]
]run
Start
Error:
    Ln 5, Col 8 in Func: _core_else
    Code 58, Abort Code 3
    Message: Wrong function reached.

]

Thanks!

**Comment by paladin-t** [comment]
Thanks a lot for your bug report!

It's a mistake in a some time ago refactoring, I've fixed it in the latest revision. Please check.

**Comment by yukini3** [comment]
It worked with the latest build. Thanks!
