### ISSUE TITLE
BASIC8 - A MY-BASIC Powered Fantasy Computer

### ISSUE THREAD

**Issue by paladin-t** [paladin-t/my_basic#19]
Hello,

It's been a while since I made MY-BASIC open source. The interpreter itself has been keeping as compact as possible. It's very interesting to see how it's involved with your creativity, I cannot make these improvements without your voice. However, I've thinking about making something playable based on the kernel.

It will be an integrated software, in which user can write code in BASIC, make sprites, maps, and music; all of this will make up - a playable video game cartridge - a packed file, no plastic or circuit :). User can test it, improve it, then share it with a community. Of course a user can download and play games created by other users. All assets are readable and editable for all users, so users can learn from each other, and derive new cartridges. You'll be familiar with this concept if you've played PICO-8. But my design is different from PICO-8, some API will be improved, there will also be some API that PICO-8 doesn't offer, the GUI is a new design, and touching friendly for future mobile porting possibility.

The first release will come out later this year, if there's no unexpected event. It will be for Windows PC at first, but it won't be difficult to port to macOS, Linux, mobiles, RasPi, etc.

I'd like to know, if you are interested to this, what kind of features you want to see the most? For example:

* Ideas about any API
* Simple 3D graphics
* Edit on mobile devices
* Can create standalone executable player for PC
* Can create standalone executable player for mobiles, and sellable to marketplaces
* Play it in web browsers
* Play it on a dedicated hardware
* Supports collision detection, and or physics reaction
* Supports LAN play
* etc.

This issue will keep open until it's ready to go, then I'll make a dev log somewhere around instead of this. Feel free to leave a message below. Any suggestions are welcome, but I won't promise I'll implement them :)

![](https://raw.githubusercontent.com/paladin-t/managed/master/ss0.png)

Sincerely
Wang Renxin

**Comment by keito940** [comment]
Yes.
If you name it, will it be "Nostalgia Heart"?

**Comment by paladin-t** [comment]
Yeah, it will be a kind of retro/vintage programming journey.

**Comment by paladin-t** [comment]
Progress update:

I've implemented all features of v1.0. Now it's testing with boundary conditions, bugfix, writing examples... that remaining to be done before launch.

The [programming manual](https://my-basic.github.io/basic8/docs/manual) is already available. But details may be changed before releasing.

**Comment by paladin-t** [comment]
The fantasy computer, named "BASIC8" will be released on early Jan. 2018 via [Steam](http://store.steampowered.com/app/767240/BASIC8/), see [homepage](https://paladin-t.github.io/b8/).

**Comment by paladin-t** [comment]
BASIC8 now available on [Steam](http://store.steampowered.com/app/767240/BASIC8/)!

**Comment by paladin-t** [comment]
All social media urls are listed at the bottom of the [homepage](https://paladin-t.github.io/b8/#system-requirements) of BASIC8. Thank you for waiting!
