### ISSUE TITLE
Etiquette...

### ISSUE THREAD

**Issue by avburpee** [paladin-t/my_basic#2]
I have added a "string in string" FIND command to my recent download of my_basic which takes a variable number of parameters ie FIND( sourcestring, searchforstring) or FIND( sourcestring, searchforstring, (int) startfromindex) . Although this was trivial I wonder if I could post it for inclusion?

I am new to GitHub so forgive me if this is an inappropriate question.
Regards,
Tony

**Comment by paladin-t** [comment]
Sure, it's appreciated to post it or email me to hellotony521[at]qq[dot]com, I'll review it then give a response.
