### ISSUE TITLE
Call a DEF purely from C

### ISSUE THREAD

**Issue by Nuker** [paladin-t/my_basic#31]
Hi paladin-t!

I loaded a BASIC script with some variable initializations and subrouting "run" into the interpreter. All this is running on a small Arduino board and I want to call the "run" subroutine from the main C loop.

The problem is, mb_eval_routine needs the pointer to void** (the AST?) to be called. At this stage I don't have this information, as the call is initiated from outside, not within the BASIC script. And in the documentation I do not find an information how to do so.

Here is where I am stuck:

int BasicScript::callRun() {
    mb_value_t routine;
    mb_value_t args[1];

    mb_get_routine(bas, l, "RUN", &routine);
    return mb_eval_routine(bas, l, routine, args, 0, NULL);   
}

**Comment by paladin-t** [comment]
Hi Nuker,

It would be better to omit it. For the current version, it can be set to any valid ast. Eg. retain a `void** l` in some entry function for further evaluation:

```c
void* ast = NULL;
entry(struct mb_interpreter_t*, void** l) {
  ast = *l;
}
call() {
  void* l = ast;
  mb_eval_routine(bas, &l, ...);
}
```

**Comment by akadjoker** [comment]
Hi paladin-t! ;)
I try to change my engine  from lua do basic but  i'm stuck on callbacks from c like lua(LOVE)

def update(time)
enddef
in c ->


 static int  basUpdate(struct mb_interpreter_t* s )
{

	void* l = NULL;
	int result = MB_FUNC_OK;

		mb_value_t routine;
		mb_value_t args[1];
		mb_value_t ret;
		mb_get_routine(s, &l, "UPDATE", &routine);  
		args[0].type = MB_DT_REAL;
		args[0].value.float_point =GetFrameTime();
		mb_make_nil(ret);
		mb_eval_routine(s, &l, routine, args, 1, &ret);
   return result;
}

and give this error :
ERROR: 
    Ln 0, Col 0
    Code 27, Abort Code 3
    Message: No return point.

tks ;)

**Comment by paladin-t** [comment]
Check this minimal example:

```c
#include "../core/my_basic.h"
#include <assert.h>
#include <stdlib.h>
#include <stdio.h>

#define CODE \
"def test(a, b)\n" \
"  print \"test\", a/b;\n" \
"  return a/b\n" \
"enddef\n" \
"setup()\n"

struct mb_interpreter_t* bas = NULL;

static void* context = NULL;

static int setup(struct mb_interpreter_t* s, void** l) {
  int result = MB_FUNC_OK;

  mb_assert(s && l);

  mb_check(mb_attempt_open_bracket(s, l));
  mb_check(mb_attempt_close_bracket(s, l));

  context = *l;

  printf("setup\n");

  return result;
}

int main(int argc, char* argv[]) {
  mb_init();
  mb_open(&bas);
  mb_reg_fun(bas, setup);

  mb_load_string(bas, CODE, true);
  mb_run(bas, true);
  {
    mb_value_t routine;
    mb_value_t args[2];
    mb_value_t ret;
    mb_make_nil(routine);
    mb_make_int(args[0], 22);
    mb_make_int(args[1], 7);
    mb_make_nil(ret);
    mb_get_routine(bas, &context, "TEST", &routine);
    mb_eval_routine(bas, &context, routine, args, 2, &ret);
    printf("%g\n", ret.value.float_point);
  }
  mb_close(&bas);
  mb_dispose();

  return 0;
}
```

**Comment by akadjoker** [comment]
now is working  , and a see the problem, firs call one function from script to get the context  ;)

**Comment by akadjoker** [comment]
Hi paladin-t!
Now working fine but is not possible to create live code with my_basic , when i change de script my app reload the script but nothing happens . i use this in duktape and lua

**Comment by paladin-t** [comment]
> when i change de script my app reload the script but nothing happens .

A new [reset-load-run](https://github.com/paladin-t/my_basic#interpreter-workflow-diagram) cycle is required to use another code

```c
...
mb_reset(...);
mb_load_string(...);
mb_run(...);
```

**Comment by akadjoker** [comment]
yes paladin ;) e change to
               mb_reset(&bas,false);
               mb_load_file(bas, script.c_str());
               mb_run(bas,false);
now live code works ;) tks

**Comment by paladin-t** [comment]
Closing this.
