### ISSUE TITLE
tests, bits and endianness

### ISSUE THREAD

**Issue by denisdemaisbr** [paladin-t/my_basic#32]
how i can:
1- run a self-tests routines?
2- official suport to 16, 32 and 64-bit ?
3- this is endianess safe? (little and big-endian cpus)

this very impressive ! congratulations!

**Comment by paladin-t** [comment]
1. no such routine yet
2. I've used the lib in a 32/64bit project and it works fine. someone had successfully run it on 16bit controller
3. the API is endian independent, so it's safe
