### ISSUE TITLE
Suspending inside a FOR-Loop breaks the loop

### ISSUE THREAD

**Issue by iUltimateLP** [paladin-t/my_basic#35]
Hi, I am implementing a simple WAIT function which waits a few seconds (non-blocking since I do it inside Unreal Engine 4), and it works great with `mb_schedule_suspend(s, MB_FUNC_SUSPEND)` and `mb_run(s, false);`
However I stumbled across a bug, suspending inside a FOR-Loop will not resume when calling mb_run. Here is my implementation of WAIT:
```cpp
int wait(struct mb_interpreter_t* s, void** l)
{
	// Will return OK
	int result = MB_FUNC_OK;

	// Holds the delay to wait (in milliseconds)
	int delay = 0;

	// Needed otherwise we can't return values!
	mb_check(mb_attempt_func_begin(s, l));
	mb_check(mb_attempt_func_end(s, l));

	// Check if an argument was passed
	if (mb_has_arg(s, l))
	{
		// Try to read an int argument into &delay
		mb_check(mb_pop_int(s, l, &delay));
	}

	// Suspend the BASIC execution until we start it again using mb_run
	mb_schedule_suspend(s, MB_FUNC_SUSPEND);
	UE_LOG(LogTemp, Log, TEXT("Suspended"));

	// Set up a timer to wait for the specified time
	float DelayTime = delay / 1000.f;
	FTimerHandle ResumeTimer;
	BasicWorldRef->GetTimerManager().SetTimer(ResumeTimer, [=]() {
		// After the UE4 timer triggered, call mb_run to resume the execution where it left of
		UE_LOG(LogTemp, Log, TEXT("Resumed"));
		mb_run(s, false);
	}, DelayTime, false);

	return result;
}
```
And here's my BASIC code to test with:
```bas
PRINT "Waiting in a loop"
FOR a=1 TO 5
  PRINT "In the loop!",a
  WAIT 1000
  NEXT a

PRINT "Finished"
```
It is printing the first "In the loop!" and "1", but then nothing happens, so it won't reach the next iteration (probably NEXT lost the reference to the for loop?)

**Comment by iUltimateLP** [comment]
Bumping this, as I want to start implementing this feature shortly. I couldn't make sense out of the my_basic source code myself, otherwise I would have tried to fix it myself. @paladin-t

**Comment by sa-tasche** [comment]
@paladin-t

**Comment by paladin-t** [comment]
The suspending feature was reserved from a very early version (almost a decade ago) of MY-BASIC. it is obsolete, and not suggested now.

Sorry this doesn't answer the question, but consider using other fiber/setcontext/coroutine lib for a workaround.

**Comment by iUltimateLP** [comment]
Ah, thanks! For me, I solved the issue by not using suspend / pause at all, but make the Basic execution completely sync and blocking, and then let it run in its own thread. Might not be the optimal solution for anyone, but for me it works!

**Comment by paladin-t** [comment]
closing for now.
