### ISSUE TITLE
Command prompt mode

### ISSUE THREAD

**Issue by yuppox** [paladin-t/my_basic#36]
How can I implement a "command prompt mode" for My Basic? This would be similar to the Python command mode, where it's possible to type in commands and have them execute immediately. Data is retained in memory but commands are not saved to a listing.

```
Example:

> a$="hello"
> print a$;
hello
> b$="world"
> print a$," ",b$;
hello world
```

Right now, it seems like I can use `mb_load_string` to run a command but then I have to use `mb_reset` after that, to remove the previous command. Of course, that also clears out the data.

**Comment by paladin-t** [comment]
It's not designed to run as REPL.
