### ISSUE TITLE
Get the name of a BASIC function inside it's C++ definition?

### ISSUE THREAD

**Issue by iUltimateLP** [paladin-t/my_basic#37]
Hey,

when implementing BASIC function in C++ using `mb_register_func()`, is there a way to retrieve the name of that function? I need that since I'm building a dynamic handler (multiple functions are registered to the same callback, and the callback needs to decide which function invoked it).

I tried to pop a string from the stack, but that resulted in an infinite loop.

Help is greatly appreciated :) Cheers, Johnny

**Comment by paladin-t** [comment]
> multiple functions are registered to the same callback, and the callback needs to decide which function invoked it

Not sure if I catch this correctly.

Each function is supposed to be unique corresponding to its registered name, and should be only registered once. But there is a way to handle different things in a single registered function dynamically. The main point to dispatch into multiple branches is to distinguish specific parameter type from other types. Eg:

```c
static int do_something(mb_interpreter_t* s, void** l) {
	int result = MB_FUNC_OK;
	mb_value_t arg;

	mb_assert(s && l);

	mb_make_nil(arg);

	mb_check(mb_attempt_open_bracket(s, l));

	mb_check(mb_pop_value(s, l, &arg)); // Pop a generic value

	...

	switch(arg.type) { // Do different things according to its type.
	case MB_DT_INT:
		...

		break;
	case MB_DT_REAL:
		...

		break;
	case MB_DT_STRING:
		...

		break;
	case MB_DT_USERTYPE: // Particularly, it's suggested that your usertype definition
		                 // should contain detailed sub-type information, so that it can
		                 // retrieve and distinguish further.
		...

		break;
	default:
		...

		break;
	}

	mb_check(mb_attempt_close_bracket(s, l));

	...

	return result;
}
```

**Comment by iUltimateLP** [comment]
Thanks for the response, that's not quite what I meant. The functions will have their own unique names, but they are all bound to the same handler, like this:

```cpp
mb_register_func("FOO", myHandler);
mb_register_func("BAR", myHandler);
```

Then inside myHandler, I need to distinguish whether it was called by the FOO or the BAR command. I hope that makes it a bit clearer :)

**Comment by iUltimateLP** [comment]
After trying a bit, I figured out that the stack trace could help like this:
```c
char* funcName;
mb_debug_get_stack_trace(s, l, &funcName, 1);
```
Is this the best way to do it, or is there a better way? Thanks!

**Comment by paladin-t** [comment]
I see. There's no built-in way to support it, but there's a workaround using userdata:

```c
struct MyUserdata {
	char* active_function;
};

MyUserdata ud;
mb_set_userdata(bas, &ud);
```

Then they are registered with different entries:

```c
mb_register_func(bas, "FOO", myFooHandler);
mb_register_func(bas, "BAR", myBarHandler);
```

The two handlers both invoke `myHandler`, which uses the userdata to tell a active context:

```c
int myFooHandler(mb_interpreter_t* s, void** l) {
	MyUserdata* ptr = NULL;
	mb_get_userdata(s, &ptr);
	ptr->active_function = "FOO"; // a) Set active function name "FOO".
	myHandler(s, l);              // b) Call `myHandler`.
	ptr->active_function = NULL;  // c) Reset it.
}

int myBarHandler(mb_interpreter_t* s, void** l) {
	MyUserdata* ptr = NULL;
	mb_get_userdata(s, &ptr);
	ptr->active_function = "BAR"; // d) Set active function name "BAR".
	myHandler(s, l);              // e) Call `myHandler`.
	ptr->active_function = NULL;  // f) Reset it.
}

int myHandler(mb_interpreter_t* s, void** l) {
	MyUserdata* ptr = NULL;
	mb_get_userdata(s, &ptr);

	// Dispatch into different branches.
	if (strcmp(ptr->active_function, "FOO") == 0) {
		// Foo called this
	} else if (strcmp(ptr->active_function, "BAR") == 0) {
		// Bar called this
	}
}
```

This is just a rough suggestion, would better to use a stack-based way instead of variable `active_function` to support nested invoking properly at a) c) and d) f).
