### ISSUE TITLE
Seperate arguments with spaces?

### ISSUE THREAD

**Issue by iUltimateLP** [paladin-t/my_basic#38]
Hey, sorry for posting so many issues, but I'm trying to get the most out of this library!

Is there a way to seperate arguments to functions by spaces instead of commas too?
Like this:
```cpp
MYFUNC 90 20 "arg3"
```
Instead of
```cpp
MYFUNC 90, 20, "arg3"
```
I've looked into _is_separator_char and tried to a whitespace char there, but it did not work unfortunately. Any idea? Thanks!
Thanks!

**Comment by paladin-t** [comment]
It's ambiguous syntax to use space as separator. Eg. it's impossible to tell if `MYFUNC a + b - c` stands for `MYFUNC a, +b - c`, `MYFUNC a + b, -c`, `MYFUNC a, b, -c` or `MYFUNC a+b-c`.

**Comment by iUltimateLP** [comment]
You're right!
