### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by julienkrief** [paladin-t/my_basic#4]
Hello Wang,

I have notice a bug,  interleaving conditions doen't works.
Example : 

int _tmain(int argc, _TCHAR* argv[])
{
	int result = MB_FUNC_OK;
	mb_init();

	char* buf1 = "IF FALSE THEN";
	char* buf2 = "IF 1 THEN";
	char* buf3 = "ENDIF";
	char* buf4 = "PRINT 1";
	char* buf5 = "ENDIF";

	struct mb_interpreter_t* bas;
	mb_open(&bas);

	mb_reg_fun(bas,maximum);

	mb_load_string(bas,buf1);
	mb_load_string(bas,buf2);
	mb_load_string(bas,buf3);
	mb_load_string(bas,buf4);
	mb_load_string(bas,buf5);

	result = mb_run(bas);

	mb_close(&bas);
	mb_dispose();

	return 0;
}

This example return 1

Regards,
Julien

**Comment by julienkrief** [comment]
Other example :

int _tmain(int argc, _TCHAR* argv[])
{
	int result = MB_FUNC_OK;
	mb_init();


	char* buf1 = "IF TRUE THEN";
	char* buf2 = "	IF TRUE THEN";
	char* buf3 = "		PRINT 2";
	char* buf4 = "	ENDIF";
	char* buf5 = "PRINT 1";
	char* buf6 = "ENDIF";

	struct mb_interpreter_t* bas;
	mb_open(&bas);

	mb_load_string(bas,buf1);
	mb_load_string(bas,buf2);
	mb_load_string(bas,buf3);
	mb_load_string(bas,buf4);
	mb_load_string(bas,buf5);

	result = mb_run(bas);


 // printf("%s", mb_ver_string());

	mb_close(&bas);
	mb_dispose();

	return 0;
}

**Comment by paladin-t** [comment]
Hi,
Thanks for your feedback. Check the latest code to solve this issue.

**Comment by julienkrief** [comment]
thanks !
