### ISSUE TITLE
STR() sometimes fails when using reals

### ISSUE THREAD

**Issue by iUltimateLP** [paladin-t/my_basic#41]
Hey there, found another bug :)

Sometimes, when calling
```bas
PRINT "my float is = " + STR(3.1415)
```
it will output "my float is = 0". I debugged it, and it seems like the `_std_str` function thinks the value is a `MB_DT_INT`, and therefore reads the `arg.value.integer` value and returns it.

**Comment by paladin-t** [comment]
Couldn't reproduce with the single line. Could you tell more details?

**Comment by iUltimateLP** [comment]
Just fresh-pulled the repo to make sure that it's not something in my project, and tested in your shell-like environment with the following script:

```bas
1]LET int = 3
2]LET float = 3.1415
3]LET string = "test"
4]PRINT "int = " + STR(int);
5]PRINT "float = " + STR(float);
6]PRINT "string = " + STR(string);
```

The result is:

```
int = 3
float = 0
string = test
```

Also, not putting the values into variables but using them directly in STR like `STR(3.1415)` does also not work.
Also, for some reason, even executing

```bas
PRINT 3.1415
```

returns 0. There has to be some weird issue regarding the conversion of floats to string.

**Comment by iUltimateLP** [comment]
Also rolled back a few commits before I made the STR() support for strings to make sure it's not that. This very small script also shows the issue:

```bas
]NEW
]LET a = 3.1415;
]PRINT "a = " + STR(a);
]RUN
a = 0
```

**Comment by paladin-t** [comment]
Thanks for the info!

The problem is caused by a locale issue. Under some locale settings (French, Spanish, etc.), comma is used as decimal point rather than dot, and locale affects other parsing/formatting behaviours.

Solved by unifying the locale. I've met same issues in some of my other projects, but didn't notice that here.

**Comment by iUltimateLP** [comment]
Thanks, great work! That fixes the issue 👍
