### ISSUE TITLE
Clearer error handling for assigning reserved keywords

### ISSUE THREAD

**Issue by iUltimateLP** [paladin-t/my_basic#43]
Hey! I found something today. Running this code:

```bas
LET val = 3
```

returns an error. I searched a bit why it error as this code is fine, but then I found out why: because "val" is a registered keyword. The error handling isn't clear in this situation, it would be great if the returned error would be "Cannot assign registered keyword" or something.

Thanks!

**Comment by paladin-t** [comment]
Added a new "Cannot assign to reserved word" error.

**Comment by iUltimateLP** [comment]
Great, thanks!
