### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by nurbles** [paladin-t/my_basic#46]
The Quick Reference and Wiki both appear to be referencing a different version of this package.  For example, they refer to the function mb_reg_fun(struct mb_interpreter_t* s, mb_func_t *f) but no such function exists in the my_basic.c/.h available here. Other functions, like mb_check(), are referenced but never documented, though at least those appear to exist in the source.

Also, some explanations and/or better, more detailed examples of integrating with a C project and extended the language by adding custom functions & routines would be a HUGE help.

[EDIT: corrected typos, removed unnecessary example code bug]

**Comment by paladin-t** [comment]
Hi,

I don't see `mb_ref_fun` in the manual or wiki. There's a `mb_reg_fun` which is a macro alias of `mb_register_func`.

Post your code plz, so we can help addressing the issue.

**Comment by nurbles** [comment]
Never mind, for now at least. So I'll close this.

When I have time I'm going to try to create a reformatted (similar to _man_ pages), indexed and cross-referenced version of the reference document (in WORD format, because that's what I know [smile]). If/when I manage to get that done, I can upload it here to be reviewed and extended, if there is any interest.
