### ISSUE TITLE
DEF/ENDDEF and GOTO?

### ISSUE THREAD

**Issue by nurbles** [paladin-t/my_basic#49]
The quick reference document explicitly prohibits mixing `DEF/ENDDEF` with `GOSUB/RETURN`, but later, when `GOTO` is described there is no mention of that restriction. To us, this implies that we should be able to use `GOTO` in a program that also contains a structured subroutine, like this:

```
def MyFunc( item )
  result = 0
  if item = 5 then
    result = 1
  end if
  return result
enddef
'[more code]
if 0 = MyFunc(3) then
  goto NotFive
end if
' [more code]
NotFive:
'[more code]
```

However, we are getting an error on the `GOTO` about mixing instructional and structured subroutines, despite our belief that we are using only the structured subroutine.

So... Is this working as expected?
- If so, it might be good to update to the quick reference to reflect the behavior.
- If not, then is there any chance it might get fixed?

**Comment by paladin-t** [comment]
It is working as expected. The `GOTO` is not mentioned in the prohibition because it is an unreturnable statement, so I didn't consider it a routine-related statement. But yes, it should be explained somewhere.
