### ISSUE TITLE
Bug with "-" and "space" character

### ISSUE THREAD

**Issue by julienkrief** [paladin-t/my_basic#5]
Hi,

When my basic is as following, i get an error : 
strike =3000
variable1= strike-customfunction()

But when i get a space between strike and customfunction() that's work :
strike =3000
variable1= strike -customfunction()

Regards,
Julien

**Comment by paladin-t** [comment]
Hi,

Thanks for feedback. Fixed the parsing bug in version 1.1.94.

Best.
WRX.

**Comment by julienkrief** [comment]
Thanks for the response !

unfortunatly the variable2 below still return 0 ...

variable1=3000
variable2= variablee1-1

==> return 0

variable1=3000
variable2= variablee1- 1

==> return 0

variable1=3000
variable2= variablee1 -1

==> return 2999

**Comment by paladin-t** [comment]
`variable1` and `variablee1` are different variables, the first one is initialized with 3000, and the second with 0.

**Comment by julienkrief** [comment]
sorry for the typo, my exemple wrong ...

var1 =3000
var2 = var1- 1

==>var2 = 0 (instead of 2999)

**Comment by paladin-t** [comment]
The bad news is whether I use `var1`, `var2` or `variable1` `variable2` or even `variablee1` `variablee2`, or in any case I put spaces, it always results 2999. Could you tell the diff of **my_basic.c** from the copy you are working on and the latest revision in the repository?
