### ISSUE TITLE
Posative (with sign) exponents not supported in REAL constants

### ISSUE THREAD

**Issue by nurbles** [paladin-t/my_basic#50]
I believe that condition on line 5883 of my_basic.c should end with `(c == '-' || c == '+')` instead of just `c == '-'` when checking for an exponent sign.  With the original code, a statement like
```
   x = 1.23E+07
```
produces an error.  With the proposed change, the constant is correctly interpreted.  I'm not familiar enough with the code to be certain that there are no unexpected effects though, so I'm suggesting the change this way.

[EDIT:  I originally and incorrectly used negative, when I mean positive.  Sorry.]

**Comment by paladin-t** [comment]
Fixed.

Thanks!
