### ISSUE TITLE
Line by Line execution

### ISSUE THREAD

**Issue by invpe** [paladin-t/my_basic#55]
Can we execute the BAS line by line instead of wait for the mb_run to finish ?

Something like:

```
while(mb_run())
{
  // We're running
  mb_next_line();
}
```

I need to ensure my BAS is executing no longer than X seconds and terminate.

**Comment by paladin-t** [comment]
it doesn't support to execute that way. can only load an entire program, execute it, then load another new.

> I need to ensure my BAS is executing no longer than X seconds and terminate.

use the `mb_debug_set_stepped_handler` function to set a debug handler, in the handler, return `MB_FUNC_BYE` when reaches some condition to interrupt it.

```c
int on_stepped(struct mb_interpreter_t* s, void** l, const char* f, int p, unsigned short row, unsigned short col) {
	if (p == -1)
		return MB_FUNC_OK;

	if (something happens)
		return MB_FUNC_BYE;

	return MB_FUNC_OK;
}
```

**Comment by invpe** [comment]
Thanks, might be a good feature to add, step by step execution could be v.handy.
