### ISSUE TITLE
mb_debug_set_stepped_handler

### ISSUE THREAD

**Issue by invpe** [paladin-t/my_basic#56]
@paladin-t 

Using: **mb_debug_set_stepped_handler**

Is it possible to identify the line at which the interpreter is currently at or at least that it is on start ?

I have noticed that on any execution, when this callback is called, the value of **row = 2**.
Does it guarantee that the execution is exactly at the start of the BAS ?

**Comment by paladin-t** [comment]
The full signature of the handler is `typedef int (* mb_debug_stepped_handler_t)(struct mb_interpreter_t* s, void** l, const char* file, int pos, unsigned short row, unsigned short col);`. The `row` should be correct most of the time, except for some cases, the interpreter cannot determine the information of source code position, then the `row` would be 0.

**Comment by invpe** [comment]
Thanks,
What is the **pos** used for ?
