### ISSUE TITLE
Calling mb_remove_reserved_func multiple times results in all functions being gone

### ISSUE THREAD

**Issue by iUltimateLP** [paladin-t/my_basic#60]
Hey, I'm experiencing a weird bug with `mb_remove_reserved_func`. In my game, I'm using the same `mb_interpreter_t` for the whole game, but everytime I'm executing code, I'm calling `mb_reset` first to clean up the state and any left over variables from last time.

My code looks something like this:
```cpp
void RunCode(const char* code)
{
	// Reset the interpreter to clean up leftover variables
	if (mb_reset(&Interpreter, false) != MB_FUNC_OK)
	{
		UE_LOG(LogRobotBrain, Error, TEXT("Error resetting interpreter!"));
	}

	// Remove keywords we need for our use
	mb_remove_reserved_func(Interpreter, "LEFT");
	mb_remove_reserved_func(Interpreter, "RIGHT");

	// Load the program into the interpreter
	int LoadResult = mb_load_string(Interpreter, code, true);

	// Run the code
	mb_run(Interpreter, true);
}
```

The first time I'm running a simple line of code, like `PRINT "Hello World"`, everything works as expected. The second time though, I'm receiving this error:
```
Error:
    Ln 1, Col 1
        Code 2, Abort Code 3
    Message: Function not exists.
```
Is calling `mb_remove_reserved_func` multiple times unsupported? It seems like it also clears other functions than LEFT and RIGHT in my case. Thanks!

**Comment by iUltimateLP** [comment]
Also, on a side note, "Function not exists." isn't valid grammer, it should read "Function does not exist." :P

**Comment by paladin-t** [comment]
> Is calling `mb_remove_reserved_func` multiple times unsupported? It seems like it also clears other functions than LEFT and RIGHT in my case. Thanks!

`mb_reset` doesn't re-register function. So the error occurs when trying to remove it twice. Try some flow like following:

```c
mb_init();
mb_open(&bas);
mb_set_error_handler(bas, _on_error);

mb_remove_reserved_func(bas, "LEFT"); // Only remove once.
mb_remove_reserved_func(bas, "RIGHT");

mb_load_string(bas, "print 22 / 7;", true);
mb_run(bas, true);

for (int i = 0; i < 10; ++i) {
	mb_reset(&bas, false);
	mb_load_string(bas, "print 22 / 7;", true);
	mb_run(bas, true);
}

mb_close(&bas);
mb_dispose();
```

> Also, on a side note, "Function not exists." isn't valid grammar, it should read "Function does not exist." :P

My bad English, will improve it :D

**Comment by iUltimateLP** [comment]
Yea I've already thought that it doesn't re-register functions, but there still seems to be some bug as it seems to clear all other functions, including PRINT too, so practically, any BASIC code fails. Try it with this example:

```cpp
mb_init();
mb_open(&bas);
mb_set_error_handler(bas, _on_error);

mb_load_string(bas, "print 22 / 7;", true);
mb_run(bas, true);

for (int i = 0; i < 10; ++i) {
	mb_reset(&bas, false);
	mb_remove_reserved_func(bas, "LEFT");
	mb_remove_reserved_func(bas, "RIGHT");
	mb_load_string(bas, "print 22 / 7;", true);
	mb_run(bas, true);
}

mb_close(&bas);
mb_dispose();
```
