### ISSUE TITLE
SHA1 in MyBasic

### ISSUE THREAD

**Issue by invpe** [paladin-t/my_basic#62]
Is it possible to write SHA1 hashing algorithm purely in MyBasic  (without any modifications) or there are some limitations?

As for the reference:

SHA1 in QBASIC: https://www.tapatalk.com/groups/qbasic/sha-1-in-qbasic-t34573.html
SHA1 Pseudocode: https://en.wikipedia.org/wiki/SHA-1#Examples_and_pseudocode

**Comment by paladin-t** [comment]
I think it is possible. MY-BASIC doesn't have built-in bitwise operations, but it's doable by combining existing ones.
