### ISSUE TITLE
ARRAY Type

### ISSUE THREAD

**Issue by invpe** [paladin-t/my_basic#63]
When declared an array:

`DIM TEST(20)
TEST(1) = 1911
PRINT TYPE(TEST(1));`

The returned type is REAL,
how to declare array of INT's ?

**Comment by paladin-t** [comment]
For some reasons, an array accepts either real or string as its content. This behaviour can be changed by enabling the `MB_SIMPLE_ARRAY` macro.

See https://github.com/paladin-t/my_basic/wiki/Customizing-macros for details.

**Comment by invpe** [comment]
Thanks, just went through it - closing.
