### ISSUE TITLE
Importing when embedding

### ISSUE THREAD

**Issue by blazer2k1** [paladin-t/my_basic#68]
So what is the setup when you want to embed the source bas files with import files, say for example the YARD game in a single executable? 

Ideally I would like to have it run as it is, where the bas files are in each file like in the shell example and also embed all of them and also use shell if possible, without making any changes to the bas files.

**Comment by paladin-t** [comment]
A [customized importer](https://github.com/paladin-t/my_basic/wiki/Customizing-an-importer) would do it, in that importer, it loads from embedded constants instead of from disk.

**Comment by blazer2k1** [comment]
Thanks @paladin-t, but the documentation there is kind of confusing perhaps that's why I missed it. 

Does this also apply with import inside an import file?

Maybe you can add the YARD game as an example or a shorter version with just several imports on how to do this?

**Comment by paladin-t** [comment]
Yes it applies to all imports.

I.e. replace the `_load_file` in [main.c](https://github.com/paladin-t/my_basic/blob/c760befb1366f94e745d96e8941978d747848a66/shell/main.c#L642-L678) with memory reading, or whatever.

**Comment by blazer2k1** [comment]
Ok so how does it work if they are loaded through `mb_load_string` like individual files that are `#define`d or say incbin'ed?

For example I have a header file that consists of all the YARD sources defined each in set of strings. 

How does import work on this setup?

```
#define START_BAS \
"import \"utils.bas\"" \
"import \"entity.bas\"" \
"import \"goal.bas\"" \
"import \"map.bas\"" \
"import \"monster.bas\"" \
"import \"npc.bas\"" \
"import \"player.bas\"" \
"import \"level.bas\"" \
...
"level.format() \n"
```
```
#define GOAL_BAS \
"REM..."
...
"endclass\n"
```

and so on..

**Comment by paladin-t** [comment]
Pseudo code for example: if the parameter `p == "start"` in `_try_import` then `mb_load_string(START_BAS)`, etc.

**Comment by blazer2k1** [comment]
Ok so how does it find and import all the embedded import files in the START_BAS embedded string?

I'm asking this because this is the most common use case of distributing a program while embedding the code like you would have in a compiled executable, since my_basic doesn't do bytecode.

**Comment by paladin-t** [comment]
Every import will be handled by the same import handler recursively.

So in that handler, it would be something like:

```
if (p == "aaa") {
  mb_load_string(AAA)
} else if (p == "bbb") {
  mb_load_string(BBB)
}
...
```

**Comment by blazer2k1** [comment]
Ok thanks I have tested a few and simple exames and get it now. It's just doing a recursive `mb_load_string` on all the files or in my case embedded string will do the job.

It should be in tree order else it will throw an error?

What I still can't figure out is you need to strip out the import file parts on the sources before loading it for it to work, otherwise it also throws an error. 

In which part in the main.c does this?

**Comment by paladin-t** [comment]
> It should be in tree order else it will throw an error?

Things must be imported before being used.

> In which part in the main.c does this?

As I already have mentioned earlier:

> "replace the `_load_file` in [main.c](https://github.com/paladin-t/my_basic/blob/c760befb1366f94e745d96e8941978d747848a66/shell/main.c#L642-L678) with memory reading, or whatever."

**Comment by blazer2k1** [comment]
>Things must be imported before being used.

I get this now yes, thanks.

>As I already have mentioned earlier...

And yes next step to the above, what im asking is where is the part in main.c where it strips out the import statements when they are being loaded. Since all the files are imported using `mb_load_string` at the end.

I did that with a file that has import of another file. It throws an error unless I remove the import statement even though the dependency file is already loaded first.

**Comment by blazer2k1** [comment]
It would be nice to provide a complete  example where a set of code is being embedded and imported like the yard demo.

part of a product as you say..

>This is effective when you need to encrypt a part of your product.

I don't think it's custom, but one of the most common use case.

**Comment by paladin-t** [comment]
There's no need to strip out the import statements. As a summarized note, what you need to do is:

1. Make sure your scripts works ok under the standard interpreter
2. Embed those scripts in C
3. Modify the already there `_load_file` or make your own import handler, which checks what the scripts import then load it, load the initial entry from `main` which imports the others

I cannot consider embedding specific scripts into an interpreter which is supposed to be a generic lib a common use case. Closing this.

**Comment by blazer2k1** [comment]
Thanks for the steps, I'll post a gists or issue to show the problem.

> I cannot consider embedding specific scripts into an interpreter which is supposed to be a generic lib a common use case.

The request is just to provide it and add it in the samples.
