### ISSUE TITLE
Write data to file

### ISSUE THREAD

**Issue by sipizolix** [paladin-t/my_basic#71]
Hi,
First of all, thank you for My-Basic. Very impressive. I'm a big fan of basic language and  I would like to port my basic stuff to My-Basic. The only showstopper that I cannot find a way to read/write files in My-Basic programs. Is it just me or this function is really missing yet? Thank you in advance.

**Comment by paladin-t** [comment]
See https://github.com/paladin-t/my_basic/wiki/File-module
