### ISSUE TITLE
Function Overloading 

### ISSUE THREAD

**Issue by blazer2k1** [paladin-t/my_basic#73]
Is it possible to do function overloading?

```
Sum(a,b)
Sum(a,b,c)
...
```

**Comment by paladin-t** [comment]
Yes, use `mb_has_arg` to check for variadic, then `mb_pop_value` and check a `mb_value_t`'s `type` filed to distinguish different types.

**Comment by blazer2k1** [comment]
Thanks @paladin-t  but I'm not that familiar yet with the api so perhaps you can also consider this issue a wiki request and add a simple how-to?
