### ISSUE TITLE
Porting to ESP8266 Arduino

### ISSUE THREAD

**Issue by yukini3** [paladin-t/my_basic#8]
Hi,
I'm porting my_basic to ESP8266 2.3.0 and Arduino 1.6.12. I found that there is an alignment error that causes system to hang. I guess pointer variables in structures must be aligned to dword. For example, the following structure, "bool_t valid;" is one byte so the following variables would be un-aligned and causes hang.

typedef struct mb_interpreter_t {
    /** Fundamental */
    bool_t valid;
    void* userdata;
    _ls_node_t* ast;

So I added three dummy "bool_t"s to align variables. Then it worked fine.

typedef struct mb_interpreter_t {
    /** Fundamental */
    bool_t valid;
    bool_t dummy1;  
    bool_t dummy2;  
    bool_t dummy3;  
    void* userdata;
    _ls_node_t* ast;

I think that it can be fixed by adding some compile switches to force align variables but I'm not familiar with those compiler switches. If you can address this issue and fix it for future release, that would be great.

Thanks!

**Comment by paladin-t** [comment]
Hi,

Thank you for posting. Looks like an alignment error indeed. Please try comment the line `#	define MB_COMPACT_MODE` in `my_basic.h`, thus the compiler should decide the alignment by itself. Hope this helps. BTW. where can I get a full specification of ESP8266?

Sincerely

**Comment by yukini3** [comment]
You can find info about esp8266 from http://esp8266.net. I will try MB_COMPAT_MODE and let you know see if it works.

**Comment by yukini3** [comment]
Hi,
I recompiled with MB_COMPAT_MODE commented out and it works fine now. Thanks a lot!
