### ISSUE TITLE
Skipping Iterator variable option

### ISSUE THREAD

**Issue by blazer2k1** [paladin-t/my_basic#80]
just curious if this can be implemented:

```
d = dict(1, "One", 2, "Two")
while move_next(iterator(d))
print get(iterator(d));
wend
```

since it's the same as:

```
f = iterator(d)
while move_next(f)
print get(f);
wend
```

w/o the iterator variable assignment

**Comment by paladin-t** [comment]
The point is an new iterator is created every time the `iterator` function gets called, and the iteration step/state is stored in it. So in your former code, an `iterator` call inside `move_next` and `get` would always point to the very first iteration cycle.
