### ISSUE TITLE
(Question) Preferred way to use print/input redirect with socket I/0

### ISSUE THREAD

**Issue by LimpingNinja** [paladin-t/my_basic#88]
Hello, this is just a question - I was looking at various ways of implementing this, I'm using my_basic as a scripting language within an online application (MUD where Admins can add custom scripting to objects) and was wondering if there was a preferred way to implement print and input redirection in this scenario. I've landed on not redirecting and simply implementing the socket comms logic exposed to MB and passing the user/socket reference to the script when invoked. In some ways, I would like to be able to use the custom handler to ease this but imagine it may not be possible without some complicated contortions.

**Comment by LimpingNinja** [comment]
Looking at the api, it seems that get_mb_userdata and set_mb_userdata are the components here that I want to utilize...

**Comment by wwiv** [comment]
Does this help?

https://github.com/paladin-t/my_basic/wiki/Redirecting-PRINT-and-INPUT
