### ISSUE TITLE
Question on import module.

### ISSUE THREAD

**Issue by wwiv** [paladin-t/my_basic#9]
Hello.

I've been trying to embed your my_basic into an existing C++ application, and most things are going very well. Thank you!!

I have a question on imports.  When using import "@modulename", it seems to only work right when the case matches the modulename.  However the case doesn't matter when specifying the full name.

Example.

I'm registering a method like this. (FOO.TEST)
```cpp
  mb_begin_module(bas, "FOO");

  mb_register_func(bas, "TEST", [](struct mb_interpreter_t* bas, void** l) -> int {
    mb_check(mb_attempt_open_bracket(bas, l));
    mb_check(mb_attempt_close_bracket(bas, l));
    std::cout << "[foo]\r\n";
    return MB_FUNC_OK;
  });

...

```

Now I can do this in my script and it works:

```bas
import "@TEST"

TEST.foo()
test.foo()
foo()

```

however this doesn't work:

```bas
import "@test"
foo()
```

Is this expected?

**Comment by paladin-t** [comment]
Hi,

Thank you for feedback! That's an omissive of case processing. Already fixed in the latest revision.

Best.
WRX

**Comment by wwiv** [comment]
Thank you, that fixed it for me.

Is there a better way to ask questions instead of opening an issue here? I have a couple of other questions if you don't mind. I'm happy to ask on here, or if there's a better place, please let me know where to ask.

**Comment by wwiv** [comment]
Thanks. it's unclear how to get registered on that site. The last "verification" question is unclear.  Others have gotten stumped by it too (see https://sourceforge.net/p/iup/mailman/iup-users/thread/1439680702.6752.3.camel@laptop/)

The question is:
" What is the corresponding keyword to FOR?:"

**Comment by paladin-t** [comment]
I can't remember, but I guess it was TO. Or did I misunderstand it?

**Comment by wwiv** [comment]
that was it. Thanks

**Comment by paladin-t** [comment]
;D

**Comment by blazer2k1** [comment]
> No official one yet. But there's a thread [here](http://www.allbasic.info/forum/index.php?topic=221.0) on All Basic.

@paladin-t you can also enable Discussions in this repo. Go to Settings, General then scroll down under Features to turn on Discussions.
